""" 
This code depicts how accurate the Monte Carlo method can be and how the Strong Law of Large Numbers (SLLN) works in practice. 
For the values of p=0.5 and p=0.75 I obtained an estimate of p by using Monte Carlo Simulation with n=100,n=1000,n=10,000. 
generate n iid Bernoulli (p) random variables B1,...,Bn and use as the estimate p̂ =1n∑i=1nBi

"""
# Import random module 
import random

# Create a function that generates a Bernoulli random variable that is itself 
# generated by using a random variable U 
def Bernoulli(p):
    # Generate a uniform random variable U
    U = random.random()
    # Check if it is <=p
    if U <= p:
        return 1
    else: 
        return 0
# Create a function that obtains an estimate of p by using Monte Carlo Simulation   
def main(n, p):
    # Initialize variable 'total' that'll be used later to find the average of
    # the random variables 
    total = 0
    
    # Use a for loop to iterate through n 
    for i in range(0, n):  
        # Generate n iid Bernoulli(p) random variables 'B'
        B = Bernoulli(p)
        # Sum and average the total Bernoulli random variables 
        total += B
    result = total/n
    return result

# Call function 
print("When n = 100 and p = .5, the estimate is: ", main(100, .5))
print("When n = 1000 and p = .5, the estimate is: ", main(1000, .5))
print("When n = 10000 and p = .5, the estimate is:", main(10000, .5))
print("When n = 100 and p = .75, the estimate is:", main(100, .75))
print("When n = 1000 and p = .75, the estimate is:", main(1000, .75))
print("When n = 10000 and p = .75, the estimate is:", main(10000, .75))
 
